// inspector.js — slide-in candidate record panel (TASK 4.3).
//
// Shows per-form STATUS from invite.formProgress (status strings only — the
// backend has no per-form timestamps, D3) grouped by the 5 categories, plus the
// overall submittedAt + progress.
//
// Two-step gate on the footer actions:
//   Review Documents      — disabled until every form is complete.
//   Complete and Download — disabled until Review Documents has run (pack cached).

import { escH, formatDate, displayName } from './util.js';
import { showToast } from './toast.js';
import { hasPack, fileFromPack, downloadPack, reviewPack } from './download.js';
import { earlyDetailsFor, fetchEarlyDetails } from './earlyDetails.js';
import { FORMS, CATEGORIES } from './forms.js';

let current = null; // the invite currently shown
// Invite ids with a review/download in flight. Gates both footer buttons for
// the *entire* async operation (not just until the next re-render), so a
// click landing between reviewPack() resolving and fileFromPack() resolving
// can't fire a second concurrent fetch/save.
const busy = new Set();
// Invite ids with a candidate-details fetch in flight — separate from `busy`
// above since this loads automatically on open, not from a footer button.
const detailsLoading = new Set();
// `${inviteId}:${sectionKey}` entries for candidate-details sub-sections HR
// has expanded — consulted when (re)rendering so a section stays open across
// re-renders (e.g. the early-details fetch settling, or Review/Download being
// clicked) instead of snapping shut every time recordHTML regenerates.
const openSections = new Set();

// Trimmed copy of the label dictionary the portal uses for downloaded
// documents (portal/js/downloads.js LABELS) — just the fields that can appear
// in the 4 gating forms' early-details payload.
const FIELD_LABELS = {
  title: 'Title', firstName: 'First name', lastName: 'Last name', dob: 'Date of birth',
  sex: 'Sex', ni: 'National Insurance number', addr1: 'Address line 1', addr2: 'Address line 2',
  city: 'Town / city', county: 'County', postcode: 'Postcode', mobile: 'Mobile number',
  homePhone: 'Home phone', email: 'Email address',
  schoolLeavingDate: 'Left full-time education',
  employmentHistory: 'Employment history', gaps: 'Gaps in employment',
  rtwEligible: 'Right to work in the UK', hasShareCode: 'Has a share code',
  shareCode: 'Share code', shareCodeDob: 'Date of birth (for share code check)',
  rtwSignedName: 'Signed by', rtwSignedDate: 'Signed on',
  hasDbs: 'Has a DBS', dbsUpdateService: 'On the Update Service',
  dbsCertNumber: 'DBS certificate number', dbsDateIssue: 'DBS date of issue',
  dbsWorkforce: 'DBS workforce', dbsDeclaration: 'DBS declaration agreed',
};
const ROW_LABELS = { employer: 'Employer', contact: 'Contact', from: 'From', to: 'To', role: 'Role', reason: 'Reason' };

function labelFor(key) {
  if (FIELD_LABELS[key]) return FIELD_LABELS[key];
  return key.replace(/[-_]/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, (c) => c.toUpperCase());
}

function displayValue(value) {
  if (value === true) return 'Yes';
  if (value === false) return 'No';
  if (value === '' || value === null || value === undefined) return '—';
  return String(value);
}

// One form's answers → form-row lines. `skipPf` drops the pf-* keys that echo
// profile fields already shown in their own "Candidate details" section
// (matches portal/js/downloads.js's formSectionHTML, which does the same).
function answerRows(data, skipPf) {
  if (!data) return '';
  const simple = [];
  const arrays = [];
  Object.entries(data).forEach(([key, value]) => {
    if (skipPf && key.startsWith('pf-')) return;
    if (Array.isArray(value)) arrays.push([key, value]);
    else simple.push([key, value]);
  });
  let html = simple
    .map(([k, v]) => `<div class="form-row"><span>${escH(labelFor(k))}</span><span>${escH(displayValue(v))}</span></div>`)
    .join('');
  arrays.forEach(([key, rows]) => {
    if (!rows.length) return;
    html += `<p class="entry-title" style="margin:10px 0 4px">${escH(labelFor(key))}</p>`;
    html += rows.map((row) => `<div class="form-row" style="align-items:flex-start"><span></span><span>${
      Object.entries(row).map(([c, v]) => `${escH(ROW_LABELS[c] || labelFor(c))}: ${escH(displayValue(v))}`).join(' · ')
    }</span></div>`).join('');
  });
  return html;
}

// One collapsible sub-section: a button header (toggles `data-toggle`'s
// matching body via onClick below) + its content, closed by default. Open/
// closed state is tracked in `openSections` (keyed per invite) so it survives
// recordHTML being regenerated by an unrelated re-render.
function toggleSection(invite, key, title, bodyHTML) {
  const isOpen = openSections.has(`${invite.id}:${key}`);
  return `<div class="cat-group">
    <button type="button" class="details-toggle" data-toggle="${key}" aria-expanded="${isOpen}">
      <h3>${escH(title)}</h3>
      <span class="chevron" aria-hidden="true">&#9656;</span>
    </button>
    <div class="details-body" id="details-${key}"${isOpen ? '' : ' hidden'}>${bodyHTML}</div>
  </div>`;
}

// Candidate details, Reg 19, and Right to Work/DBS — sent early by the portal
// once those 4 gating forms are all complete (GET /invites/:id/early-details).
// Each renders as its own open/close section; before the candidate has sent
// them, opening a section just shows a "not yet available" note.
function candidateDetailsHTML(invite) {
  const loading = detailsLoading.has(invite.id);
  const details = earlyDetailsFor(invite.id);
  const loadingBody = `<div class="skel" style="width:70%;margin-bottom:8px"></div><div class="skel" style="width:50%"></div>`;
  const notReadyBody = `<p class="none">Not yet available — the candidate hasn't finished their
    details, Regulation 19, Right to Work and DBS forms yet.</p>`;

  const bodyFor = (data, skipPf) => {
    if (loading) return loadingBody;
    if (!details) return notReadyBody;
    return answerRows(data, skipPf) || '<p class="none">No answers yet.</p>';
  };

  return [
    toggleSection(invite, 'profile', 'Candidate details', bodyFor(details?.profile, false)),
    toggleSection(invite, 'reg19', 'Regulation 19 — Employment History', bodyFor(details?.reg19, true)),
    toggleSection(invite, 'rtwDbs', 'Right to Work & DBS',
      loading ? loadingBody : !details ? notReadyBody
        : (answerRows(details.rightToWork, true) + answerRows(details.dbs, true)) || '<p class="none">No answers yet.</p>'),
  ].join('');
}

function statusMark(status) {
  if (status === 'completed') return '<span class="tick">Completed</span>';
  if (status === 'in_progress') return '<span class="dash">In progress</span>';
  return '<span class="none">Not started</span>';
}

export function recordHTML(invite) {
  const reviewed = hasPack(invite.id);
  const allFormsComplete = invite.formsTotal > 0 && invite.formsComplete === invite.formsTotal;
  const purged = invite.status === 'received' && !reviewed;
  const isBusy = busy.has(invite.id);

  const groups = CATEGORIES.map((cat) => {
    const rows = FORMS.filter((f) => f.category === cat).map((f) => {
      const st = invite.formProgress?.[f.id];
      return `<div class="form-row"><span>${escH(f.name)}</span>${statusMark(st)}</div>`;
    }).join('');
    return `<div class="cat-group"><h3>${escH(cat)}</h3>${rows}</div>`;
  }).join('');

  const reviewDisabled = isBusy
    ? 'disabled title="Working…"'
    : purged
      ? 'disabled title="Pack purged from relay"'
      : !allFormsComplete
        ? 'disabled title="All forms must be completed before you can review"'
        : '';
  const completeDisabled = isBusy
    ? 'disabled title="Working…"'
    : purged
      ? 'disabled title="Pack purged from relay"'
      : !reviewed
        ? 'disabled title="Review the documents first"'
        : '';

  return `
    <button class="btn btn-sm btn-secondary" data-act="close">Back</button>
    <h2>${escH(displayName(invite))} — ${escH(invite.role)}</h2>
    <p class="muted">Status: ${escH(invite.status)} · Submitted: ${formatDate(invite.submittedAt)}</p>
    <p>Progress: ${invite.formsComplete} / ${invite.formsTotal} forms complete</p>
    ${candidateDetailsHTML(invite)}
    ${groups}
    <div style="margin-top:18px;display:flex;gap:8px;flex-wrap:wrap">
      <button class="btn btn-secondary" data-act="review" ${reviewDisabled}>Review Documents</button>
      <button class="btn btn-primary" data-act="complete-download" ${completeDisabled}>Complete and Download ↓</button>
    </div>`;
}

function close() {
  document.getElementById('inspector').hidden = true;
  document.getElementById('inspector-scrim').hidden = true;
  current = null;
  // Lets the dashboard table pick up anything that changed while open (e.g. a
  // pack download here reveals Confirm Receipt back in the row).
  window.dispatchEvent(new CustomEvent('inspector-closed'));
}

async function onClick(e) {
  const btn = e.target.closest('button');
  if (!btn || !current) return;

  if (btn.dataset.act === 'close') return close();

  if (btn.dataset.toggle) {
    const key = `${current.id}:${btn.dataset.toggle}`;
    const wasOpen = openSections.has(key);
    if (wasOpen) openSections.delete(key); else openSections.add(key);
    // Direct DOM toggle (no full re-render needed) so this stays snappy and
    // doesn't interact with the busy/loading re-render paths below.
    const body = document.getElementById(`details-${btn.dataset.toggle}`);
    if (body) body.hidden = wasOpen;
    btn.setAttribute('aria-expanded', String(!wasOpen));
    return;
  }

  // Snapshot the invite at click time. `current` can change out from under
  // this handler (panel closed or a different candidate opened) while the
  // awaits below are in flight — operate on the stable local instead.
  const invite = current;
  const reentrant = btn.dataset.act === 'review' || btn.dataset.act === 'complete-download';

  if (reentrant) {
    // busy (not just this button's disabled attribute) gates the whole async
    // operation: a re-render mid-flight (openRecord swaps in a fresh button
    // node) must not hand the user a live button while work is still pending.
    if (busy.has(invite.id)) return;
    busy.add(invite.id);
    openRecord(invite); // reflect the busy state immediately
  }

  try {
    if (btn.dataset.act === 'review') {
      await reviewPack(invite.id);
      await fileFromPack(invite.id, 'All_Forms_Combined.html');
      showToast('Documents reviewed');
    } else if (btn.dataset.act === 'complete-download') {
      await downloadPack(invite.id, displayName(invite));
      showToast('Pack downloaded');
    }
  } catch (err) {
    if (err.status !== 401) showToast(err.message || 'Download failed');
  } finally {
    if (reentrant) {
      busy.delete(invite.id);
      // Single re-render at settlement: reflects the real cached state
      // (reviewed/downloaded) even if a later step in the try failed, and
      // only if the panel is still showing this same invite.
      if (current && current.id === invite.id) openRecord(invite);
    }
  }
}

export function openRecord(invite) {
  // Only a genuinely new open (not the re-render below, once the fetch
  // settles) should kick off a fetch — otherwise a candidate who hasn't sent
  // early details yet (a 404, not an error) would re-fetch in an infinite
  // loop: fetch resolves → re-render → "new" fetch → resolves → re-render...
  const isNewOpen = !(current && current.id === invite.id);
  current = invite;
  const panel = document.getElementById('inspector');
  panel.innerHTML = recordHTML(invite);
  panel.hidden = false;
  document.getElementById('inspector-scrim').hidden = false;
  // Wire once per open (innerHTML replaced each time, so (re)bind the panel).
  panel.onclick = onClick;
  document.getElementById('inspector-scrim').onclick = close;

  // Candidate details load automatically (no button) — only successful fetches
  // are cached, so an invite that hasn't sent them yet is retried on the next
  // genuine "View record" open rather than being stuck forever.
  if (isNewOpen && !earlyDetailsFor(invite.id) && !detailsLoading.has(invite.id)) {
    detailsLoading.add(invite.id);
    fetchEarlyDetails(invite.id)
      .catch((err) => { if (err.status !== 401) showToast(err.message || 'Could not load candidate details'); })
      .finally(() => {
        detailsLoading.delete(invite.id);
        if (current && current.id === invite.id) openRecord(invite); // isNewOpen will be false here
      });
  }
}
